# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=15)),
                ('review', models.TextField(max_length=5000)),
                ('month', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('rate', models.CharField(max_length=5)),
                ('sentiment', models.CharField(max_length=5)),
            ],
        ),
    ]
