# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('CountryCode', models.CharField(max_length=50)),
                ('Population', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=50)),
                ('Population', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyRevenue', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=15)),
                ('review', models.TextField(max_length=5000)),
                ('date', models.DateField()),
                ('sentiment', models.CharField(max_length=5)),
            ],
        ),
    ]
