# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsites',
            name='review',
            field=models.TextField(max_length=5000),
        ),
    ]
